#!/bin/bash

rm fixedfa.txt

IFS=

touch fixedfa.txt
count=0

while read wholeline
do
	if [[ ${wholeline:0:1} == ">" ]]; then
		count=$((count+1))
		if [[ $count == 1 ]] then
			printf "$wholeline\n"
		else
			printf "\n$wholeline\n"
		fi

	else 
		printf "$wholeline"
	fi >> fixedfa.txt

done < mock_NCBI.fasta 
cat fixedfa.txt
	
