#!/bin/bash

#Go through the file showing an index counter and the country

IFS=$'\t'

index=0
while read name email city birth_day birth_month birth_year country
do
    index=$((index+1))
    echo -e "#\t${index}\t${name}\t${city}\t${country}"
done > example_people_data.tsv

# Go through the file showing an index counter, name, city and the country, but without the header and blanks lines this time

index=0
tail -n +2 example_people_data.tsv | while read name email city birth_day birth_month birth_year country
do
	if [[ -z "$name" || -z "$email" || -z "$city" || -z "$birth_day" || -z "$birth_month" || -z "$birth_year" || -z "$country" ]]; then
        continue
	index=index

	fi 

        index=$((index+1))
        echo -e "\#\t${index}\t${name}\t${city}\t${country}"
done

#Put people into separate files: a different file for each country

tail -n +2 example_people_data.tsv | while read name email city birth_day birth_month birth_year country
do
        if [[ -z "$name" ]] || [[ -z "$email" ]] || [[ -z "$city" ]] || [[ -z "$birth_day" ]] || [[ -z "$birth_month" ]] || [[ -z "$birth_year" ]] || [[ -z "$country" ]]; then
                index=index
                continue
        fi      
        mkdir -p "$country"
        echo -e  "$name $email $city $birth_day $birth_month $birth_year $country" >> $country/people.txt
done

#Work out how many people were born in October, and where are they from, output the list of people

index=0
while read name email city birth_day birth_month birth_year country
do
        if [[ -z "$name" ]] || [[ -z "$email" ]] || [[ -z "$city" ]] || [[ -z "$birth_day" ]] || [[ -z "$birth_month" ]] || [[ -z "$birth_year" ]] || [[ -z "$country" ]]; then
                continue
                index=index
        fi
        if [[ "$birth_month"="October" ]]; then
                index=$((index+1))
                echo -e "$index" "$name" "$country"
        fi

done > example_people_data.tsv

#Work out how many people were born in October, and where are they from, output as multiple lists

index=0
while read name email city birth_day birth_month birth_year country
do
        if [[ -z "$name" ]] || [[ -z "$email" ]] || [[ -z "$city" ]] || [[ -z "$birth_day" ]] || [[ -z "$birth_month" ]] || [[ -z "$birth_year" ]] || [[ -z "$country" ]]; then
                continue
                index=index
        fi
        if [[ "$birth_month"="October" ]]; then
                index=$((index+1))
                printf "%s\t%s\t%s" "$index" "$name" "$country" >> "$country.list"
        fi

done > example_people_data.tsv 

